openapi: "3.0.0"
info: 
  title: Tshirt Store API 
  description: Backend API for ecom site
  version: 1.1.0
  contact: 
    email: nitinchoudharyn14@gmail.com
    url: "http://localhost/api/v1"

servers:
  - url: "{protocol}://localhost:4000/api/{version}"
    description: Localhost - Dev Envirnoment
    variables:
      version:
        enum:
          - v1
          - v2
        default: v1
      protocol:
        enum:
          - http
          - https
        default: http

components:
  securitySchemes:
    cookieAuth:
      type: apikey
      in: cookie
      name: token
    BearerAuth:
      type: http
      scheme: bearer


paths:
  /dummy:
    get:
      tags:
        - Home 
      summary: returns a greet message from 
      responses:
        200:
          description: All good success
          content:
            application/json:
              schema:
                type: string
                example: "mystring"
        400:
          description: Bad request
        500:
          description: Internal Server Error

